[package]
name = "group_profile"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "group_profile"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
group_profile_integrity = { workspace = true }
